swagger: "2.0"
info:
  title: Order and Admin API
  version: "1.0.0"
  description: API documentation for order management and admin functionalities.

paths:
  /api/person/v1/registerUser:
    post:
      summary: Registers a user
      parameters:
        - in: body
          name: user
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              email:
                type: string
      responses:
        200:
          description: Successful
        400:
          description: Bad Request

  /api/person/v1/loginUser:
    post:
      summary: Logs in a registered user
      parameters:
        - in: body
          name: login
          required: true
          schema:
            type: object
            properties:
              userInput:
                type: string
              password:
                type: string
      responses:
        200:
          description: Successful
        400:
          description: Bad Request

  /api/person/v1/logoutUser:
    delete:
      summary: Logs out a user and ends the session
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: Session token
      responses:
        200:
          description: Successful
        401:
          description: Unauthorized

  /api/order/v1/order/create:
    post:
      summary: Creates an order
      parameters:
        - in: header
          name: token
          required: true
          description: Authentication token
          schema:
            type: string
        - in: body
          name: order
          required: true
          schema:
            type: object
            properties:
              personUid:
                type: string
                format: uuid
                description: GUID of the person placing the order
                nullable: true
              itemList:
                type: array
                items:
                  type: object
                  properties:
                    itemId:
                      type: string
                      description: Item ID
                    itemQuantity:
                      type: integer
                      description: Quantity to order
                    itemSeller:
                      type: string
                      format: uuid
                      description: Seller GUID
                    itemPrice:
                      type: number
                      description: Price of the item
                    priceDiscount:
                      type: number
                      description: Discount applied to the item
      responses:
        200:
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: order ID
        400:
          description: Bad Request
        401:
          description: Unauthorized

  /api/order/v1/order/fetchxml/{orderUid}:
    get:
      summary: Retrieves XML representation of an order
      parameters:
        - name: orderUid
          in: path
          required: true
          type: string
          format: uuid
          description: GUID of the order
      responses:
        200:
          description: XML data retrieved
        401:
          description: Unauthorized

  /api/order/v1/order/retrieve/all/{personUid}:
    get:
      summary: Gets and lists the details of all orders for a specific person
      parameters:
        - name: personUid
          in: path
          required: true
          type: string
          format: uuid
          description: GUID of the person
      responses:
        200:
          description: Successful
        401:
          description: Unauthorized

  /api/order/v1/order/cancel:
    post:
      summary: Cancels an order
      parameters:
        - in: body
          name: body
          description: Order UID to cancel
          required: true
          schema:
            type: object
            properties:
              orderUid:
                type: string
                format: uuid
            required:
              - orderUid
      responses:
        200:
          description: Order canceled successfully
        400:
          description: Could not cancel order
        401:
          description: Unauthorized
        500:
          description: Internal server error

  
  /api/order/v1/complete:
    post:
      summary: Marks an order as completed
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Order UID to complete
          required: true
          schema:
            type: object
            properties:
              orderUid:
                type: string
                format: uuid
            required:
              - orderUid
      responses:
        200:
          description: Order completed successfully
        400:
          description: Bad request
        401:
          description: Unauthorized


  /api/order/v1/clear:
    delete:
      summary: Clears the database
      responses:
        200:
          description: Database cleared successfully
        500:
          description: Internal server error
